FROM riobueno/php-apache:7.2


RUN apt-get update \
	&& apt-get install -y \
		libmemcachedutil2 \
		libmemcached-dev \
        memcached \
	&& apt-get update -y \
    && rm -rf /var/lib/apt/lists/* 

RUN docker-php-source extract \

# Install igbinary (for more efficient serialization in redis/memcached)
    && for i in $(seq 1 3); do pecl install -o igbinary && s=0 && break || s=$? && sleep 1; done; (exit $s) \
    && docker-php-ext-enable igbinary \
#   \
# Install redis (manualy build in order to be able to enable igbinary)
#    && for i in $(seq 1 3); do pecl install -o --nobuild redis && s=0 && break || s=$? && sleep 1; done; (exit $s) \
#    && cd "$(pecl config-get temp_dir)/redis" \
#    && phpize \
#    && ./configure --enable-redis-igbinary \
#    && make \
#    && make install \
#    && docker-php-ext-enable redis \
#    && cd - \
#    \
# Install memcached (manualy build in order to be able to enable igbinary)
    && for i in $(seq 1 3); do echo no | pecl install -o --nobuild memcached && s=0 && break || s=$? && sleep 1; done; (exit $s) \
    && cd "$(pecl config-get temp_dir)/memcached" \
    && phpize \
    && ./configure --enable-memcached-igbinary \
    && make \
    && make install \
    && docker-php-ext-enable memcached \
    && cd - \
    \
# Delete source & builds deps so it does not hang around in layers taking up space
    && pecl clear-cache \
    && rm -Rf "$(pecl config-get temp_dir)/*" \
    && docker-php-source delete \
    && apt-get purge -y --auto-remove
# PHP configuration
#COPY config/php.ini /usr/local/etc/php/


RUN  a2enmod rewrite headers

