FROM php:7.2-apache
LABEL maintainer="Jefferson Riobueno <riobueno.jr@gmail.com>"

RUN apt-get update \
	&& apt-get install -y libmcrypt-dev \
		libjpeg62-turbo-dev \
		libpcre3-dev \
		libpng16-16 \
		libfreetype6-dev \
		libxml2-dev \
		libicu-dev \
		libzip-dev \
		default-mysql-client \
#		libxpm4  \
		wget \
		unzip \
	&& apt-get update -y \
    && rm -rf /var/lib/apt/lists/* 

RUN docker-php-source extract \
# Extract php source and install missing extensions
    #&& docker-php-source extract \
	&& docker-php-ext-install iconv gd mbstring intl zip mysqli pdo_mysql soap \
	&& if [ -d "/usr/src/php/ext/mcrypt" ]; then docker-php-ext-install mcrypt; fi \
	&& if [ -d "/usr/src/php/ext/mysql" ]; then docker-php-ext-install mysql; fi \
	&& if [ -d "/usr/src/php/ext/opcache" ]; then docker-php-ext-install opcache; fi \
    && docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-source delete 
#   && cp /usr/src/php/php.ini-production ${PHP_INI_DIR}/php.ini \
#    \
# Apache configuration
#RUN if [ -x "$(command -v apache2-foreground)" ]; then a2enmod rewrite; fi

# PHP configuration
COPY config/php.ini /usr/local/etc/php/


RUN  a2enmod rewrite headers

