FROM riobueno/php-apache:7.2

#RUN docker-php-source extract \

# Install igbinary (for more efficient serialization in redis/memcached)
#    && for i in $(seq 1 3); do pecl install -o igbinary && s=0 && break || s=$? && sleep 1; done; (exit $s) \
#    && docker-php-ext-enable igbinary \
#   \
# Install redis (manualy build in order to be able to enable igbinary)
#    && for i in $(seq 1 3); do pecl install -o --nobuild redis && s=0 && break || s=$? && sleep 1; done; (exit $s) \
#    && cd "$(pecl config-get temp_dir)/redis" \
#    && phpize \
#    && ./configure --enable-redis-igbinary \
#    && make \
#    && make install \
#    && docker-php-ext-enable redis \
#    && cd - \
#    \

RUN mkdir -p /usr/src/php/ext/redis \
    && curl -L https://github.com/phpredis/phpredis/archive/3.0.0.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1 \
    && echo 'redis' >> /usr/src/php-available-exts \
    && docker-php-ext-install redis

RUN  a2enmod rewrite headers

