version: "3"
services:
    DB:
        image: 'mysql:5.5.62'
        container_name: TEST-mysql
        volumes:
        - ./d-mysql:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - TZ=America/Lima
            - MYSQL_USER=root
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=database
        command: 
            - mysqld 
            - --character-set-server=utf8 
            - --collation-server=utf8_slovenian_ci  
        ports: 
            - "33071:3306"