FROM php:7.2-apache
LABEL maintainer="Jefferson Riobueno <riobueno.jr@gmail.com>"

RUN apt-get update \
	&& apt-get install -y \
		libwebp-dev \
		libjpeg62-turbo-dev \
		libpng-dev libxpm-dev \
		libfreetype6-dev \
		libmcrypt-dev \
		libpcre3-dev \
		libxml2-dev \
		libicu-dev \
		libzip-dev \
		default-mysql-client \
		libxslt1.1 \
		libbz2-dev \
		imagemagick \
		wget \
		unzip \
		zlib1g-dev \
	&& apt-get update -y \
    && rm -rf /var/lib/apt/lists/* 

RUN docker-php-source extract \
# Extract php source and install missing extensions
    #&& docker-php-source extract \
	&& if [ -d "/usr/src/php/ext/mcrypt" ]; then docker-php-ext-install mcrypt; fi \
	&& if [ -d "/usr/src/php/ext/mysql" ]; then docker-php-ext-install mysql; fi \
    && docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
    && docker-php-ext-configure calendar \
    && docker-php-ext-configure gd \
    --with-gd \
    --with-webp-dir \
    --with-jpeg-dir \
    --with-png-dir \
    --with-zlib-dir \
    --with-xpm-dir \
    --with-freetype-dir \
	&& docker-php-ext-install gd iconv mbstring intl zip mysqli pdo_mysql soap exif bz2 calendar gettext shmop sockets sysvmsg sysvsem sysvshm wddx\
	&& docker-php-source delete 

#   && cp /usr/src/php/php.ini-production ${PHP_INI_DIR}/php.ini \
#    \
# Apache configuration
#RUN if [ -x "$(command -v apache2-foreground)" ]; then a2enmod rewrite; fi

# PHP configuration
COPY config/php.ini /usr/local/etc/php/

# Install and enable xDebug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

# Prevent error in nginx error.log
RUN touch /var/log/xdebug_remote.log
RUN chmod 777 /var/log/xdebug_remote.log

# Xdebug setup
RUN echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_autostart=true" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_mode=req" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_log=/var/log/xdebug_remote.log" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#RUN echo "xdebug.idekey=phpstorm" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_connect_back=Off" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

COPY DOCKER/script.sh /var/docker/script.sh

RUN chmod +x /var/docker/script.sh

RUN  a2enmod rewrite headers

